# Generated by Django 4.2.6 on 2024-01-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_direccionenvio_ccomuna_id_alter_direccionenvio_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
