# Generated by Django 4.2.6 on 2024-01-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_modelo_rename_categoria_marca_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marca',
            table='Marca',
        ),
    ]
