# Generated by Django 4.2.6 on 2024-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_marca_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
