# Generated by Django 4.2.6 on 2024-01-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_producto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
    ]
