# Generated by Django 4.2.6 on 2024-01-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_producto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
    ]
