# Generated by Django 4.2.6 on 2024-01-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_producto_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
    ]
