# Generated by Django 4.2.6 on 2024-01-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_producto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.marca'),
            preserve_default=False,
        ),
    ]
